name = input("enter the name :")
Noun = input("enter the relation :")
emotion = input("enter the emotion :")
place = input("enter the place name :")
verb = input("enter the verb :")
food = input("enter the food :")
print("--------------------------------The Made Libs Game By F4ll-------------------------")
print("Dear " + name)
print("You are the Best " + Noun + "Ever ")
print("I feel so " + emotion + "to Have You ")
print("You as my " + Noun + "I want you ")
print("TO celebrate this " + emotion + " Ocassion ")
print("by going to the " + place + " And eating " + food)
print("I sure " + verb + " You ")
